openapi: 3.0.0
info:
  title: Automotora API
  description: API para la gestión de automóviles en una automotora
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /autos:
    post:
      summary: Crear un nuevo automóvil
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto-Peticion'
      responses:
        '201':
          description: Automóvil creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto-Respuesta'
        '400':
          description: Petición errónea
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
    get:
      summary: Obtener la lista de todos los automóviles
      responses:
        '200':
          description: Lista de automóviles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auto-Respuesta'
  /autos/{id}:
    get:
      summary: Obtener detalles de un automóvil específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del automóvil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto-Respuesta'
        '404':
          description: Automóvil no encontrado
    put:
      summary: Actualizar la información de un automóvil específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto-Respuesta'
      responses:
        '200':
          description: Información del automóvil actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto-Respuesta'
        '404':
          description: Automóvil no encontrado
    delete:
      summary: Eliminar un automóvil específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Automóvil eliminado exitosamente
        '404':
          description: Automóvil no encontrado
components:
  schemas:
    Auto-Respuesta:
      type: object
      properties:
        id:
          type: integer
          example: 1
        marca:
          type: string
          example: Toyota
        modelo:
          type: string
          example: Corolla
        año:
          type: integer
          example: 2020
        color:
          type: string
          example: Rojo
        precio:
          type: integer
          example: 10000
    Auto-Peticion:
      type: object
      properties:
        marca:
          type: string
          example: Toyota
        modelo:
          type: string
          example: Corolla
        año:
          type: integer
          example: 2020
        color:
          type: string
          example: Rojo
        precio:
          type: integer
          example: 10000
    Error:
      type: object
      properties:
        mensaje:
          type: string
          example: El campo precio debe ser entero

